### ISSUE TITLE
Printing of debug data fails when remelting is included

### ISSUE THREAD

**Issue by MattRolchigo** [LLNL/ExaCA#104]
Print debug routine (printing of view data following initialization) needs to be modified to account for the fact that the multilayer views characterizing temperature data (CritTimeStep, UndercoolingChange, LayerID) are filled on a layer by layer basis when remelting is included (without remelting, the entirety of these views are initialized before the first layer, and the appropriate data is printed).

**Comment by streeve** [comment]
disabled in #105
