### ISSUE TITLE
Seg faults for problems of type R.

### ISSUE THREAD

**Issue by jwwtc** [LLNL/ExaCA#157]
Hello. Regarding the problems of type R, I've tried reducing the cell size to a number that evenly divides the temperature data mesh size. However, every time I do that, I run into a segmentation fault. All the other examples run perfectly fine. 
Do you think there is an hardware issue on my side? I'm running the simulations on WSL 2, with a free space of 34GBs and swap space of 8 GBs. Thanks in advance.

**Comment by MattRolchigo** [comment]
This was likely related to the just now-merged #154 if you were trying to run Inp_SimpleRaster.txt - do you still get the error with the current version of the repository?

**Comment by jwwtc** [comment]
I pulled the changes and it now works. Thanks! 
By the way, do you have plans of enabling cell size reduction (relative to the ht mesh size) for the RM problems?
If that's possible in the first place, of course.

**Comment by MattRolchigo** [comment]
Actually, I'm hoping to eventually remove problem type R to begin with (or rather, type R is redefined as type RM), as simulation type R isn't particularly useful for most practical cases. Unfortunately, it isn't easily possible to refine the mesh for simulations of type RM, but the hope is that we'll also have a means of easily generating temperature data of that type at the needed resolution that will be linked to this repository if/when problem type R is removed

**Comment by streeve** [comment]
Closing as fixed - feel free to reopen or create a new issue to continue discussion as needed

**Comment by jwwtc** [comment]
As far as I understand, for simulating cases with hundreds of layers, it would be important for the cell size to be set far below the value of the ht mesh size; given that ht simulations for those cases require a relatively large mesh size (certainly larger than 1-5um). Is that the case?

> the hope is that we'll also have a means of easily generating temperature data of that type at the needed resolution that will be linked to this repository if/when problem type R is removed

Would it be possible, in that case, to generate temperature data of a lower mesh size (equal to the cell size) even for the now defined RM problems? 
Thanks again!

**Comment by MattRolchigo** [comment]
@jwwtc The codes that we've been using (which will soon be released as open source) are capable of generating data at a mesh size equal to the CA cell size, on the order of 1-5 µm. Once they are available, we will add this information to our README along with github links. Unfortunately, the inability to easily interpolate data from a coarse mesh to a fine mesh comes from the fact that the temperature data isn't actually "temperatures", but rather values for time (the time at which a location reached the liquidus while heating or cooling) and cooling rates - these can't easily be interpolated when regions of the simulation remelt different numbers of times, or when cells that undergo melting/solidification border those that don't (i.e., cells that have no data).

**Comment by jwwtc** [comment]
@MattRolchigo Being able to generate data at the necessary cell size would be important. Thank you.
And I now understand the difficulty of doing the interpolation in this case.

Regarding plotting EBSD-like IPFs for cross-sections, after importing the EBSD data (for example [this](https://github.com/jwwtc/ExaCA/blob/master/analysis/results/CrossSection-YZ528_IPFCrossSection.txt) file) to MTEX and labeling the columns as phi1, Phi, phi2, Phase, y, z,  I get a "Could not detect file format" error. Am I doing something wrong, is it an issue with the format itself or is the issue related to MTEX?
