### ISSUE TITLE
Introduce pybind11 bindings for analysis tools

### ISSUE THREAD

**Issue by rcarson3** [LLNL/ExaCA#19]
Per an earlier ExaAM meeting, I mentioned that you could probably add python bindings through [pybind11](https://github.com/pybind/pybind11/) for your post-processing scripts to allow people to natively interact with your data in python. I was just looking over your post-processing scripts, and it looks like it should be relatively straight-forward to do. 

I think I should have some time either later this week or next week to do this. So, I can open a PR for it as well. I believe once the basic structure for the bindings is set-up it should be fairly straight-forward to add any additional functionality you might have to them.

@MattRolchigo and @streeve let me know if you'd be fine with this and if so I'll get that PR thrown together in the near future.

**Comment by streeve** [comment]
Sounds great to me

**Comment by rcarson3** [comment]
This might be a bit more complicated than I was expecting...

So, I'm going through this in a bit more details and one thing pops out to me that you're imposing kokkos on yourself for this post-processing. However, you never actually use kokkos in the post-processing except to have it for some view type operations. It seems that you could replace that with a macro or something like: https://github.com/mfem/mfem/blob/master/linalg/dtensor.hpp . The only reason I bring this is up is because of the kokkos initialize and finalize calls. I do slightly worry about those in a python context as it appears they affect global states. It seems based on various issues on the kokkos repo that this would be an issue...

If you really do need it, I might end up duplicating the various code you have in the post-processing, remove the kokkos portions and print stuff, and just have the calculated data returned to python. It might be sub-optimal if you decide to have these calculations on the GPU later on, but I can't think of a good way to handle the unsafe portion of kokkos init/fin and not have users break things in python land...

**Comment by streeve** [comment]
I don't have any experience with it, but there are (relatively limited) Kokkos python bindings: https://github.com/kokkos/pykokkos

I don't know if that helps with any issues you're bringing up. I pushed for Kokkos in the postprocessing to try to avoid this being a bottleneck for large scale runs (of course we need to move more of it to parallel kernels). 

Maybe we need a call to discuss this

**Comment by rcarson3** [comment]
Sadly, I don't think that'll help with this issue... Honestly, it seems all to boil down to the fact that Kokkos, while a powerful library, has a brittle interface in-regards to the init/fin portion of things. 

I think I can come up with a solution that should work for everyone. However, it will probably require some major refactoring of the analysis related tools to allow both a python and kokkos backend to exist nice and happy together. Before I start that yeah it might be worth having a call to discuss this maybe sometime next week.

**Comment by streeve** [comment]
Closing - stale
