### ISSUE TITLE
Print routine flexibility

### ISSUE THREAD

**Issue by MattRolchigo** [LLNL/ExaCA#232]
Following the object-oriented reorganization of the code, the `Print` struct can be significantly reorganized to be made more adaptable for printing of any field from `Temperature`, `CellData`, or any other 3D field not yet organized into structs. It is current disorganized and limited to printing specific views. Printing should be organized as follows:

- There should be two types of printing: 1) Intermediate (i.e., the start of each layer, the end of each layer, and intermediate time steps) and 2) Final (End of simulation). "Init" print is the same as the first frame from the intermediate print. These intermediate files should be named so that the corresponding time values are included
- All views for printing are either "full domain" views or "current layer" views. These should be printed to separate files for a given print frame. For intermediate printing, "full domain" views are printed only to the top of the current layer

**Comment by streeve** [comment]
@MattRolchigo closed by #280 ?

**Comment by MattRolchigo** [comment]
Yep, forgot to link it
