### ISSUE TITLE
Adding second materials

### ISSUE THREAD

**Issue by GuoChi-Li** [LLNL/ExaCA#281]
Dear Developers,

I want to add the second materials in the ExaCA, making it possible to simulate the different materials' situations. I have read some of the codes and am thinking about some modifications. Here are my preliminary ideas about this.

I have some data that comes from Flow3D software. The data contains coordinates, second material fraction, temperature, cooling rate, temperature gradient, etc. This is an example file when time = 0.  [0.0.csv](https://github.com/LLNL/ExaCA/files/13902743/0.0.csv)

The example simulation result for the two materials is shown as follows.
[Video result](https://www.dropbox.com/scl/fi/3486mu0pg8qfiebrog0q3/Linear-scanning-strategy.mp4?rlkey=31po4pjd0rjg6sx4e7v9th2yd&dl=0)

#### Add materials for the initial assignment, like the temperature
Specifying the file name, read layer-wise material, TempFilesInSeries
The change will be like ...
```
std::vector <std::string> material_paths
bool LayerwiseMaterialRead = false;
int MaterialFilesInSeries = 0;
...
```

### Material input file
It contains the x, y, and z coordinates and the fraction of the second materials at certain positions. Assuming the materials don't interact with each other.

For example
```
x, y, z, fraction of second material
0, 0, 0, 0.0
1, 1, 1, 0.5
...
```

### Modifying the CAinitialize.hpp
Adding checkMaterialFileFormat function like checkTemperatureFileFormat.

# Questions:
Does the current CA algorithm support this modification?
If not, where can I start to read and modify the codes?

**Comment by MattRolchigo** [comment]
I have tentative plans to incorporate multiphase solidification in the future, but in a different way. My thought was combining the nucleation and interfacial response structs into one `material` struct, where you could have a vector of this information where each element in the vector is a different material. The `cell data` struct would include a new field, `phase_id`, associating each cell with a given material (`phase_id` data would also be communicated across MPI ranks for cell capture events at MPI processor boundaries the way things like `grain_id` are currently). With this approach, you could theoretically seed the substrate using grain and phase IDs and create a simulation where multiple phases grow from the substrate and nucleate from the liquid.

In your case, what information are you looking to get out of an ExaCA simulation with multiple phases? Do you know the morphology of the solidified material in the video that you showed (for example, is the second phase appearing in the interdendritic liquid? Or is it some kind of irregular eutectic structure?)

**Comment by GuoChi-Li** [comment]
I haven't read the nucleation and interfacial codes, but combining them into one `material` struct sounds like a better approach. Will the `phase_id` be assigned by the outside file like the temperature is currently? When will this functionality be released because my PhD thesis is related to this topic?

I am looking to get the morphology of the grains, such as column grains and dendritic structures. For the preliminary idea, I am planning to choose two materials that don't interact with each other chemically (i.e., they don't form intermetallic compounds). We have a team that can provide the experimental specimens and get the EBSD/OM data from the specimens. For eutectic materials, a [paper](https://www.nature.com/articles/s41524-022-00824-5) did this.

**Comment by MattRolchigo** [comment]
Sorry for the late response. While I do plan on updating ExaCA to account for separate phases with separate nucleation and interfacial response behavior, ExaCA is a "grain scale" code - "sub scale" details such as explicit dendrite branches, solute profile, and eutectic spacing are only approximated.

For example, the paper you linked is able to model those details because of Equation 4, which calculates solute diffusion. In ExaCA, the interfacial response function assumes some solute profile through the interfacial response function rather than solve Equation 4. If you want phase fractions, grain size and shape statistics, and texture, ExaCA may be useful to you. But if you want to know things like the dendrite arm spacing or dendrite shape, you'll likely be better off using a code that models the solidification problem at the "sub scale"

**Comment by GuoChi-Li** [comment]
Thank you for your time. I really appreciated it.

Currently, ExaCA uses the interfacial response function, which uses the undercooling temperature versus tip velocity function, which implicitly contains part of the solute profile. However, if I want to study the concentration profile, I need to change this part of the codes or use other packages. Am I correct?

**Comment by streeve** [comment]
> However, if I want to study the concentration profile, I need to change this part of the codes or use other packages. Am I correct?

Including those physics in ExaCA would take substantial effort to the point that I would only suggest a different code (existing or writing a new one)

**Comment by GuoChi-Li** [comment]
Thank you. I will consider different codes.
