### ISSUE TITLE
Temperature files are missing

### ISSUE THREAD

**Issue by lreigbua** [LLNL/ExaCA#310]
Hello,

I believe the temperature inputs for the R/RM examples are missing. Is there any way to access these?

Thank you for making this code available.

Regards,

**Comment by MattRolchigo** [comment]
As mentioned in the README (https://github.com/LLNL/ExaCA/blob/master/README.md), the temperature files needed to run the `SingleLine` and `TwoLineTwoLayer` examples are available in a separate data repository: https://github.com/LLNL/ExaCA-Data. Were there other missing temperature files you are referring to?

**Comment by streeve** [comment]
No worries, let us know if we can help with anything else in a new issue. I went ahead and clarified a few things in the linked PR
