### ISSUE TITLE
make temperature path available

### ISSUE THREAD

**Issue by mikejwg** [LLNL/ExaCA#32]
appreciate it very much if the temperature files can be downloaded in the temperature path.

**Comment by streeve** [comment]
We are in the process of creating a new, separate repository for these (relatively large) temperature files. We would then welcome updates and contributions to that new repo or additional discussion on how to use those files here.

**Comment by MattRolchigo** [comment]
I've been told that a new "ExaCA-data" repository can be created, though I'm still waiting for that to be done on the admin's end. I plan on putting temperature files for the "SimpleRaster" and "AMBenchMultilayer" problems in that repo once it is created and I have access

**Comment by streeve** [comment]
@MattRolchigo let's add a link in the readme to the new repo when it's populated, and close this issue with that PR

**Comment by streeve** [comment]
Example temperature data is now available: https://github.com/LLNL/ExaCA-Data
