### ISSUE TITLE
can the code simulate Columnar to equiaxed （CTE）grain transition？ 

### ISSUE THREAD

**Issue by mikejwg** [LLNL/ExaCA#37]
Dear developer,
We inputted different thermal gradient and cooling rate according to the solidification map to simulate columnar to equiaxed CTE
grain transition. But we could not predict equiaxed grains using the code. Any suggestions on this topic.
Thanks very much.

**Comment by MattRolchigo** [comment]
I've used the code to simulate the CET in the past - mostly for directional solidification. For example, if you run the example problem "Inp_DirSolidification.txt" without modification, you should get a microstructure that is approximately 70% nucleated grains, and these grains have primarily equiaxed shapes (though are still somewhat elongated in the thermal gradient/Z direction). For which input problem are you attempting to obtain the CET?

**Comment by mikejwg** [comment]
Thanks for your reply. I inputted  the thermal gradient as  100 K/m and the cooling rate as 100 K/s.  We hope to simulate equiaxed grains that are about the same size in three directions, but the grains are always stretched very long in the direction of the temperature gradient.

**Comment by MattRolchigo** [comment]
With a thermal gradient of 100 K/m and a cooling rate of 100 K/s, what cell
size and time step ratio are you using? I believe what may be happening is
that while the conditions may promote equiaxed solidification in theory,
your domain is too small for the solidification front to reach the
nucleation undercooling (or a steady-state undercooling for growth). If you
increase your cell size, you should see grains nucleating and growing.
Additionally, decreasing the time step ratio and decreasing your mean
nucleation undercooling should help as well
