### ISSUE TITLE
Is this code capable of simulating  the subsequent microstructural evolution of the grain structures during post-processing processes

### ISSUE THREAD

**Issue by mikejwg** [LLNL/ExaCA#375]
Dear authors,
may I ask if this code is capable of simulating both the solidification microstructure in additive manufacturing and the subsequent microstructural evolution of the grain structures during post-processing processes? And if, within a temperature history file, the significant difference in time scales between the additive manufacturing time (for example, in the LPBF process, where the computational time scales applicable by CA (Cellular Automaton) methods may be relatively small) and the post-processing time (characterized by longer holding periods and slower cooling rates) could potentially lead to difficulties in the calculations.
mike John

**Comment by MattRolchigo** [comment]
As of now, this code is only capable of predicting the as-solidified grain structure - grain boundaries do not move once the temperature is the associated cells falls outside of the freezing range. As you mentioned, the difference in relevant length/time scales for modeling solid-solid phase transformations during solidification versus reheating is significant, and a different code would probably be better suited for that purpose. We have loosely discussed the possibility of utilizing additional time-temperature history to predict solid-solid grain growth as an ExaCA post-processing step, but we don't have any immediate plans to develop such a capability.

**Comment by mikejwg** [comment]
Thanks for your reply.
