### ISSUE TITLE
Unit test for InputReadFromFile must be run from same directory as executable

### ISSUE THREAD

**Issue by MattRolchigo** [LLNL/ExaCA#67]
No paths are currently given for the two examples files - Inp_DirSolidification.txt and Inp_SpotMelt.txt - that were installed in the build directory for unit testing. The unit test for InputReadFromFile must currently be run from the same directory as the unit test executable, this should be remedied by providing a path to these files

**Comment by streeve** [comment]
@MattRolchigo I believe this was fixed in #89 - can this be closed?

**Comment by streeve** [comment]
ping @MattRolchigo
